### ISSUE TITLE
error help

### ISSUE THREAD

**Issue by Alduuur** [ArkSeyonet/esx_identity#3]
ERROR [ERROR] [MySQL] An error happens on MySQL for query "UPDATE users SET lastPosition = @actualPos WHERE identifier = @identifier {identifier=steam:11000011404b243;actualPos=[120.50745391846,6606.314453125,31.923246383667]}": Unknown column 'lastPosition' in 'field list'
[ERROR] [MySQL] An error happens on MySQL for query "UPDATE users SET lastPosition = @actualPos WHERE identifier = @identifier {identifier=steam:110000117f4025b;actualPos=[123.47071075439,6611.3837890625,31.85898399353]}": Unknown column 'lastPosition' in 'field list'

**Comment by ArkSeyonet** [comment]
That is not an esx_identity error. The script never interacts with lastPosition
