### ISSUE TITLE
Error MySQL isDead 

### ISSUE THREAD

**Issue by Skreperek** [ArkSeyonet/esx_identity#5]
[ERROR] [MySQL] An error happens on MySQL for query "SELECT isDead FROM users WHERE identifier=@identifier {@identifier=steam:11000010f483d13}": Unknown column 'isDead' in 'field list' 

How can i fix that?
Its spamming in console.

**Comment by ArkSeyonet** [comment]
My script does not search for an isDead column through SQL?
