### ISSUE TITLE
Black screen on reconnect

### ISSUE THREAD

**Issue by ali-exacute** [ArkSeyonet/esx_identity#7]
so , i just installed this script and its really nice and simple
but i found some bug when i join , screen will freeze on a black screen
tried to reconnect and it worked again , but my position was changed to default(spawn) position
any idea how to fix black screen?
i will provide more info as i am testing it RN

Edit : so , i found out that everything is working but my screen is all black
every command work , every plugin work even my character walk and do everything...

edit2: disabling loading screen didnt help so it wasnt the problem

edit3: when you create character and disconnect normally , you will connect back without problem , but when you quit fivem(crash-force close F8quit) this issue will happen

**Comment by ArkSeyonet** [comment]
If your spawn position is not saving then you need to edit the database because position needs to be VARCHAR(255) in es_extended.sql  

It does not control spawn position it only receives the same information from es_extended.

**Comment by ArkSeyonet** [comment]
Closing from lack of response.
